### ISSUE TITLE
still same error for next.js

### ISSUE THREAD

**Issue by Lurtt** [40818419/react-code-input#66]
Hi, I would like to use this cool component but I am getting same error as in #63 
It happen everytime I import the component..

using `"react-code-input": "^3.8.0"`

```
TypeError: Cannot read property 'href' of undefined
    at getURL (/Users/lukas/Repositories/xxx/node_modules/next/dist/lib/utils.js:130:30)
    at new Router (/Users/lukas/Repositories/xxx/node_modules/next/dist/lib/router/router.js:139:29)
    at _callee3$ (/Users/lukas/Repositories/xxx/node_modules/next/dist/server/render.js:256:22)
    at tryCatch (/Users/lukas/Repositories/xxx/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/lukas/Repositories/xxx/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/lukas/Repositories/xxx/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/lukas/Repositories/xxx/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/lukas/Repositories/xxx/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at <anonymous>
```

**Comment by Lurtt** [comment]
Sry, it helps a bit.
If I use dynamic import it works but when I add prop like onChange, style, inputStyle it happens again.

```
import dynamic from 'next/dynamic'
const ReactCodeInput = dynamic(import('react-code-input'))

...
<ReactCodeInput
  type="number"
  fields={5}
  onChange={e => console.log('xxx', e.target.value)}
  style={{ display: 'grid' }}
  inputStyle={{}}
/>
...
```
